name: _Contributor Details

on:
    workflow_dispatch:

jobs:
    update-contributor-details:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Make script executable
              run: chmod +x .github/workflows/scripts/fetch_contributor_details.sh

            - name: Fetch contributor details
              run: .github/workflows/scripts/fetch_contributor_details.sh
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add _data/contributors.json
                  git diff --quiet && git diff --staged --quiet || git commit -m "Update contributor details"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
