name: _Update GitHub Contributors

on:
    workflow_dispatch:

jobs:
    github-contributors:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - name: Make script executable
              run: chmod +x .github/workflows/scripts/fetch_contributors.sh

            - name: Update contributors
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO_OWNER: ${{ github.repository_owner }}
                  REPO_NAME: ${{ github.event.repository.name }}
              run: ./.github/workflows/scripts/fetch_contributors.sh

            # Remove temp file before creating PR
            - name: Clean up temp file
              run: rm -f .temp.json

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Update GitHub contributors
                  title: 'chore: Update GitHub contributors'
                  body: |
                      This PR updates the GitHub contributors in examples.json.

                      This is an automated PR created by the GitHub Contributors workflow.
                  branch: update/github-contributors
                  base: trunk
                  delete-branch: true
